[package]
authors = ["Agnetha Korevaar <>"]
name = "nucleo-f411re"
version = "0.4.0"
edition = "2018"
description = "Board Support crate for the STM32 NUCLEO-f411RE development board"
repository = "https://github.com/akorevaar/nucleo-f411re"
readme = "README.md"
license = "0BSD"
keywords = [
    "arm",
    "cortex-m",
    "stm32f411",
    "nucleo",
    "template",
]
categories = [
    "embedded",
    "no-std",
]

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.7"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dependencies.stm32f4xx-hal]
default-features = false
features = ["rt", "stm32f411"]
version = "0.8.0"

[dev-dependencies]
nb = "0.1.1"
hd44780-driver = "0.3.0"
tpa2016d2 = "0.2.0"
embedded-graphics = { version = "0.6.0" }
rtt-target = {version = "0.2.0", features = ["cortex-m"] }
panic-rtt-target = {version = "0.1.0", features = ["cortex-m"] }

[dev-dependencies.cortex-m-rtfm]
version = "0.5"

[dev-dependencies.segment-display]
version = "0.1.0"

[dev-dependencies.epd-waveshare]
version = "0.4.0"
features = ["graphics"]

[features]
default = ["rt"]
rt = []

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
